apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-psp-role
rules:
  - apiGroups:
      - policy
    resourceNames:
      - nvidia-network-operator-privileged
    resources:
      - podsecuritypolicies
    verbs:
      - use
