apiVersion: v2
name: network-operator
version: 1.2.0-beta.1
kubeVersion: '>= 1.17.0'
appVersion: v1.2.0-beta.1
description: Nvidia network operator
type: application
keywords:
  - gpu-direct
  - rdma
home: https://mellanox.github.io/network-operator
sources:
  - https://github.com/Mellanox/network-operator
dependencies:
- condition: nfd.enabled
  name: node-feature-discovery
  repository: "http://kubernetes-sigs.github.io/node-feature-discovery/charts"
  version: 0.10.1
- condition: sriovNetworkOperator.enabled
  name: sriov-network-operator
  repository: "https://k8snetworkplumbingwg.github.io/helm-charts/release"
  version: 1.1.0

