{{if eq .RuntimeSpec.OSName "rhcos"}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nv-peer-mem-driver
  namespace: {{ .RuntimeSpec.Namespace }}
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged
{{end}}
