{{if eq .RuntimeSpec.OSName "rhcos"}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ib-kubernetes
  namespace: {{ .RuntimeSpec.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ib-kubernetes
  namespace: {{ .RuntimeSpec.Namespace }}
subjects:
- kind: ServiceAccount
  name: ib-kubernetes
  namespace: {{ .RuntimeSpec.Namespace }}
userNames:
- system:serviceaccount:{{ .RuntimeSpec.Namespace }}:ib-kubernetes
{{end}}
