{{if eq .RuntimeSpec.OSName "rhcos"}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ipoib-cni
  namespace: {{ .RuntimeSpec.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ipoib-cni
  namespace: {{ .RuntimeSpec.Namespace }}
subjects:
- kind: ServiceAccount
  name: ipoib-cni
  namespace: {{ .RuntimeSpec.Namespace }}
userNames:
- system:serviceaccount:{{ .RuntimeSpec.Namespace }}:ipoib-cni
{{end}}
