name: "Build"
on: [push, pull_request]

jobs:
  lint-code:
    name: golangci-lint
    runs-on: ubuntu-20.04
    permissions:
      contents: read
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: checkout
        uses: actions/checkout@v3
      - name: lint
        run: make lint
  lint-docker:
    name: hadolint
    runs-on: ubuntu-20.04
    permissions:
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: lint Dockerfile
        run: make lint-dockerfile
  lint-helm:
    name: helm lint
    runs-on: ubuntu-20.04
    permissions:
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: lint helm chart
        run: make lint-helm
  unit-tests:
    name: Unit-tests
    runs-on: ubuntu-20.04
    permissions:
      contents: read
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: checkout
        uses: actions/checkout@v3
      - name: test
        run: make test-coverage
